// Following System-UI Theme Specification.
// ref: https://github.com/system-ui/theme-specification
//
// Thus, it might be useful when you use stitches.
// ref: https://stitches.dev/docs/tokens#using-tokens
// (Warning: Style might be flicker when you use SSR w/stiches.)
//
// All tokens used here are defined in https://www.krds.go.kr/html/site/style/style_07_popup.html

const commonTheme = {
  fontSizes: {
    base: 'var(--krds-font-size-base)',
    pc: {
      display: {
        large: 'var(--krds-pc-font-size-display-large)',
        medium: 'var(--krds-pc-font-size-display-medium)',
        small: 'var(--krds-pc-font-size-display-small)',
      },
      body: {
        large: 'var(--krds-pc-font-size-body-large)',
        medium: 'var(--krds-pc-font-size-body-medium)',
        small: 'var(--krds-pc-font-size-body-small)',
        xsmall: 'var(--krds-pc-font-size-body-xsmall)',
      },
      label: {
        large: 'var(--krds-pc-font-size-label-large)',
        medium: 'var(--krds-pc-font-size-label-medium)',
        small: 'var(--krds-pc-font-size-label-small)',
        xsmall: 'var(--krds-pc-font-size-label-xsmall)',
      },
      heading: {
        large: 'var(--krds-pc-font-size-heading-large)',
        medium: 'var(--krds-pc-font-size-heading-medium)',
        small: 'var(--krds-pc-font-size-heading-small)',
        xsmall: 'var(--krds-pc-font-size-heading-xsmall)',
        xxsmall: 'var(--krds-pc-font-size-heading-xxsmall)',
        xlarge: 'var(--krds-pc-font-size-heading-xlarge)',
      },
      navigationTitle: {
        medium: 'var(--krds-pc-font-size-navigation-title-medium)',
        small: 'var(--krds-pc-font-size-navigation-title-small)',
      },
      navigationDepth: {
        medium: 'var(--krds-pc-font-size-navigation-depth-medium)',
        small: 'var(--krds-pc-font-size-navigation-depth-small)',
        mediumBold: 'var(--krds-pc-font-size-navigation-depth-medium-bold)',
        smallBold: 'var(--krds-pc-font-size-navigation-depth-small-bold)',
      },
    },
    mobile: {
      display: {
        large: 'var(--krds-mobile-font-size-display-large)',
        medium: 'var(--krds-mobile-font-size-display-medium)',
        small: 'var(--krds-mobile-font-size-display-small)',
      },
      body: {
        large: 'var(--krds-mobile-font-size-body-large)',
        medium: 'var(--krds-mobile-font-size-body-medium)',
        small: 'var(--krds-mobile-font-size-body-small)',
        xsmall: 'var(--krds-mobile-font-size-body-xsmall)',
      },
      label: {
        large: 'var(--krds-mobile-font-size-label-large)',
        medium: 'var(--krds-mobile-font-size-label-medium)',
        small: 'var(--krds-mobile-font-size-label-small)',
        xsmall: 'var(--krds-mobile-font-size-label-xsmall)',
      },
      heading: {
        large: 'var(--krds-mobile-font-size-heading-large)',
        medium: 'var(--krds-mobile-font-size-heading-medium)',
        small: 'var(--krds-mobile-font-size-heading-small)',
        xsmall: 'var(--krds-mobile-font-size-heading-xsmall)',
        xxsmall: 'var(--krds-mobile-font-size-heading-xxsmall)',
        xlarge: 'var(--krds-mobile-font-size-heading-xlarge)',
      },
      navigationTitle: {
        medium: 'var(--krds-mobile-font-size-navigation-title-medium)',
        small: 'var(--krds-mobile-font-size-navigation-title-small)',
      },
      navigationDepth: {
        medium: 'var(--krds-mobile-font-size-navigation-depth-medium)',
        small: 'var(--krds-mobile-font-size-navigation-depth-small)',
        mediumBold: 'var(--krds-mobile-font-size-navigation-depth-medium-bold)',
        smallBold: 'var(--krds-mobile-font-size-navigation-depth-small-bold)',
      },
    },
  },
  gap: {
    gap1: 'var(--krds-gap-1)',
    gap2: 'var(--krds-gap-2)',
    gap3: 'var(--krds-gap-3)',
    gap4: 'var(--krds-gap-4)',
    gap5: 'var(--krds-gap-5)',
    gap6: 'var(--krds-gap-6)',
    gap7: 'var(--krds-gap-7)',
    gap8: 'var(--krds-gap-8)',
    gap9: 'var(--krds-gap-9)',
    gap10: 'var(--krds-gap-10)',
    gap11: 'var(--krds-gap-11)',
    gap12: 'var(--krds-gap-12)',
  },
  gapLayout: {
    pc: {
      headerBreadcrumb: 'var(--krds-pc-gap-layout-header-breadcrumb)',
      leftContents: 'var(--krds-pc-gap-layout-left-contents)',
      contentsRight: 'var(--krds-pc-gap-layout-contents-right)',
      h1H2: 'var(--krds-pc-gap-layout-h1-h2)',
      h2H2: 'var(--krds-pc-gap-layout-h2-h2)',
      h2H3: 'var(--krds-pc-gap-layout-h2-h3)',
      h3H3: 'var(--krds-pc-gap-layout-h3-h3)',
      h3H4: 'var(--krds-pc-gap-layout-h3-h4)',
      h4H4: 'var(--krds-pc-gap-layout-h4-h4)',
      h4H5: 'var(--krds-pc-gap-layout-h4-h5)',
      h5H5: 'var(--krds-pc-gap-layout-h5-h5)',
      titleBodySmall: 'var(--krds-pc-gap-layout-title-body-small)',
      titleBodyMedium: 'var(--krds-pc-gap-layout-title-body-medium)',
      titleBodyLarge: 'var(--krds-pc-gap-layout-title-body-large)',
      breadcrumbH1: 'var(--krds-pc-gap-layout-breadcrumb-h1)',
      contentsFooter: 'var(--krds-pc-gap-layout-contents-footer)',
      textTextLarge: 'var(--krds-pc-gap-layout-text-text-large)',
      textTextMedium: 'var(--krds-pc-gap-layout-text-text-medium)',
      textTextSmall: 'var(--krds-pc-gap-layout-text-text-small)',
      imageTextSmall: 'var(--krds-pc-gap-layout-image-text-small)',
      imageTextMedium: 'var(--krds-pc-gap-layout-image-text-medium)',
      imageTextLarge: 'var(--krds-pc-gap-layout-image-text-large)',
    },
    mobile: {
      headerBreadcrumb: 'var(--krds-mobile-gap-layout-header-breadcrumb)',
      leftContents: 'var(--krds-mobile-gap-layout-left-contents)',
      contentsRight: 'var(--krds-mobile-gap-layout-contents-right)',
      h1H2: 'var(--krds-mobile-gap-layout-h1-h2)',
      h2H2: 'var(--krds-mobile-gap-layout-h2-h2)',
      h2H3: 'var(--krds-mobile-gap-layout-h2-h3)',
      h3H3: 'var(--krds-mobile-gap-layout-h3-h3)',
      h3H4: 'var(--krds-mobile-gap-layout-h3-h4)',
      h4H4: 'var(--krds-mobile-gap-layout-h4-h4)',
      h4H5: 'var(--krds-mobile-gap-layout-h4-h5)',
      h5H5: 'var(--krds-mobile-gap-layout-h5-h5)',
      titleBodySmall: 'var(--krds-mobile-gap-layout-title-body-small)',
      titleBodyMedium: 'var(--krds-mobile-gap-layout-title-body-medium)',
      titleBodyLarge: 'var(--krds-mobile-gap-layout-title-body-large)',
      breadcrumbH1: 'var(--krds-mobile-gap-layout-breadcrumb-h1)',
      contentsFooter: 'var(--krds-mobile-gap-layout-contents-footer)',
      textTextLarge: 'var(--krds-mobile-gap-layout-text-text-large)',
      textTextMedium: 'var(--krds-mobile-gap-layout-text-text-medium)',
      textTextSmall: 'var(--krds-mobile-gap-layout-text-text-small)',
      imageTextSmall: 'var(--krds-mobile-gap-layout-image-text-small)',
      imageTextMedium: 'var(--krds-mobile-gap-layout-image-text-medium)',
      imageTextLarge: 'var(--krds-mobile-gap-layout-image-text-large)',
    },
  },
  lineHeights: {
    none: 'var(--krds-line-height-none)',
    base: 'var(--krds-line-height-base)',
  },
  fonts: {
    base: 'var(--krds-font-family-base)',
  },
  fontWeights: {
    regular: 'var(--krds-font-weight-regular)',
    bold: 'var(--krds-font-weight-bold)',
  },
  fontOffsets: {
    underline: 'var(--krds-font-underline-offset)',
  },
  letterSpacings: {
    none: 'var(--krds-letter-spacing-none)',
    wide: 'var(--krds-letter-spacing-wide)',
  },
  transitions: {
    base: 'var(--krds-transition-base)',
    fade: 'var(--krds-transition-fade)',
    collapse: 'var(--krds-transition-collapse)',
    collapseWidth: 'var(--krds-transition-collapse-width)',
  },
  contents: {
    size: 'var(--krds-contents-size)',
    paddingX: 'var(--krds-contents-padding-x)',
    wrapSize: 'var(--krds-contents-wrap-size)',
  },
  boxShadows: {
    outline: 'var(--krds-box-shadow-outline)',
    outlineInset: 'var(--krds-box-shadow-outline-inset)',
  },
  zoom: {
    small: 'var(--krds-zoom-small)',
    medium: 'var(--krds-zoom-medium)',
    large: 'var(--krds-zoom-large)',
    xlarge: 'var(--krds-zoom-xlarge)',
    xxlarge: 'var(--krds-zoom-xxlarge)',
  },
  padding: {
    padding1: 'var(--krds-padding-1)',
    padding2: 'var(--krds-padding-2)',
    padding3: 'var(--krds-padding-3)',
    padding4: 'var(--krds-padding-4)',
    padding5: 'var(--krds-padding-5)',
    padding6: 'var(--krds-padding-6)',
    padding7: 'var(--krds-padding-7)',
    padding8: 'var(--krds-padding-8)',
    padding9: 'var(--krds-padding-9)',
    padding10: 'var(--krds-padding-10)',
  },
  radii: {
    xsmall1: 'var(--krds-radius-xsmall1)',
    xsmall2: 'var(--krds-radius-xsmall2)',
    xsmall3: 'var(--krds-radius-xsmall3)',
    small1: 'var(--krds-radius-small1)',
    small2: 'var(--krds-radius-small2)',
    small3: 'var(--krds-radius-small3)',
    medium1: 'var(--krds-radius-medium1)',
    medium2: 'var(--krds-radius-medium2)',
    medium3: 'var(--krds-radius-medium3)',
    medium4: 'var(--krds-radius-medium4)',
    large1: 'var(--krds-radius-large1)',
    large2: 'var(--krds-radius-large2)',
    xlarge1: 'var(--krds-radius-xlarge1)',
    xlarge2: 'var(--krds-radius-xlarge2)',
    max: 'var(--krds-radius-max)',
  },
  sizes: {
    height1: 'var(--krds-size-height-1)',
    height2: 'var(--krds-size-height-2)',
    height3: 'var(--krds-size-height-3)',
    height4: 'var(--krds-size-height-4)',
    height5: 'var(--krds-size-height-5)',
    height6: 'var(--krds-size-height-6)',
    height7: 'var(--krds-size-height-7)',
    height8: 'var(--krds-size-height-8)',
    height9: 'var(--krds-size-height-9)',
    height10: 'var(--krds-size-height-10)',
    height11: 'var(--krds-size-height-11)',
  },
  breakpoints: {
    small: '360px',
    medium: '768px',
    large: '1024px',
    xlarge: '1280px',
    xxlarge: '1440px',
  },
  iconSizes: {
    xsmall: 'var(--krds-icon--size-xsmall)',
    small: 'var(--krds-icon--size-small)',
    medium: 'var(--krds-icon--size-medium)',
    large: 'var(--krds-icon--size-large)',
    xlarge: 'var(--krds-icon--size-xlarge)',
  },
} as const;

const lightTheme = {
  ...commonTheme,
  colors: {
    primary5: 'var(--krds-color-light-primary-5)',
    primary10: 'var(--krds-color-light-primary-10)',
    primary20: 'var(--krds-color-light-primary-20)',
    primary30: 'var(--krds-color-light-primary-30)',
    primary40: 'var(--krds-color-light-primary-40)',
    primary50: 'var(--krds-color-light-primary-50)',
    primary60: 'var(--krds-color-light-primary-60)',
    primary70: 'var(--krds-color-light-primary-70)',
    primary80: 'var(--krds-color-light-primary-80)',
    primary90: 'var(--krds-color-light-primary-90)',
    primary95: 'var(--krds-color-light-primary-95)',

    secondary5: 'var(--krds-color-light-secondary-5)',
    secondary10: 'var(--krds-color-light-secondary-10)',
    secondary20: 'var(--krds-color-light-secondary-20)',
    secondary30: 'var(--krds-color-light-secondary-30)',
    secondary40: 'var(--krds-color-light-secondary-40)',
    secondary50: 'var(--krds-color-light-secondary-50)',
    secondary60: 'var(--krds-color-light-secondary-60)',
    secondary70: 'var(--krds-color-light-secondary-70)',
    secondary80: 'var(--krds-color-light-secondary-80)',
    secondary90: 'var(--krds-color-light-secondary-90)',
    secondary95: 'var(--krds-color-light-secondary-95)',

    gray0: 'var(--krds-color-light-gray-0)',
    gray5: 'var(--krds-color-light-gray-5)',
    gray10: 'var(--krds-color-light-gray-10)',
    gray20: 'var(--krds-color-light-gray-20)',
    gray30: 'var(--krds-color-light-gray-30)',
    gray40: 'var(--krds-color-light-gray-40)',
    gray50: 'var(--krds-color-light-gray-50)',
    gray60: 'var(--krds-color-light-gray-60)',
    gray70: 'var(--krds-color-light-gray-70)',
    gray80: 'var(--krds-color-light-gray-80)',
    gray90: 'var(--krds-color-light-gray-90)',
    gray95: 'var(--krds-color-light-gray-95)',
    gray100: 'var(--krds-color-light-gray-100)',

    alphaBlack100: 'var(--krds-color-light-alpha-black-100)',
    alphaBlack75: 'var(--krds-color-light-alpha-black-75)',
    alphaBlack50: 'var(--krds-color-light-alpha-black-50)',
    alphaBlack25: 'var(--krds-color-light-alpha-black-25)',
    alphaBlack10: 'var(--krds-color-light-alpha-black-10)',
    alphaBlack0: 'var(--krds-color-light-alpha-black-0)',

    alphaWhite100: 'var(--krds-color-light-alpha-white-100)',
    alphaWhite75: 'var(--krds-color-light-alpha-white-75)',
    alphaWhite50: 'var(--krds-color-light-alpha-white-50)',
    alphaWhite25: 'var(--krds-color-light-alpha-white-25)',
    alphaWhite10: 'var(--krds-color-light-alpha-white-10)',
    alphaWhite0: 'var(--krds-color-light-alpha-white-0)',

    danger5: 'var(--krds-color-light-danger-5)',
    danger10: 'var(--krds-color-light-danger-10)',
    danger20: 'var(--krds-color-light-danger-20)',
    danger30: 'var(--krds-color-light-danger-30)',
    danger40: 'var(--krds-color-light-danger-40)',
    danger50: 'var(--krds-color-light-danger-50)',
    danger60: 'var(--krds-color-light-danger-60)',
    danger70: 'var(--krds-color-light-danger-70)',
    danger80: 'var(--krds-color-light-danger-80)',
    danger90: 'var(--krds-color-light-danger-90)',
    danger95: 'var(--krds-color-light-danger-95)',

    information5: 'var(--krds-color-light-information-5)',
    information10: 'var(--krds-color-light-information-10)',
    information20: 'var(--krds-color-light-information-20)',
    information30: 'var(--krds-color-light-information-30)',
    information40: 'var(--krds-color-light-information-40)',
    information50: 'var(--krds-color-light-information-50)',
    information60: 'var(--krds-color-light-information-60)',
    information70: 'var(--krds-color-light-information-70)',
    information80: 'var(--krds-color-light-information-80)',
    information90: 'var(--krds-color-light-information-90)',
    information95: 'var(--krds-color-light-information-95)',

    warning5: 'var(--krds-color-light-warning-5)',
    warning10: 'var(--krds-color-light-warning-10)',
    warning20: 'var(--krds-color-light-warning-20)',
    warning30: 'var(--krds-color-light-warning-30)',
    warning40: 'var(--krds-color-light-warning-40)',
    warning50: 'var(--krds-color-light-warning-50)',
    warning60: 'var(--krds-color-light-warning-60)',
    warning70: 'var(--krds-color-light-warning-70)',
    warning80: 'var(--krds-color-light-warning-80)',
    warning90: 'var(--krds-color-light-warning-90)',
    warning95: 'var(--krds-color-light-warning-95)',

    success5: 'var(--krds-color-light-success-5)',
    success10: 'var(--krds-color-light-success-10)',
    success20: 'var(--krds-color-light-success-20)',
    success30: 'var(--krds-color-light-success-30)',
    success40: 'var(--krds-color-light-success-40)',
    success50: 'var(--krds-color-light-success-50)',
    success60: 'var(--krds-color-light-success-60)',
    success70: 'var(--krds-color-light-success-70)',
    success80: 'var(--krds-color-light-success-80)',
    success90: 'var(--krds-color-light-success-90)',
    success95: 'var(--krds-color-light-success-95)',

    point5: 'var(--krds-color-light-point-5)',
    point10: 'var(--krds-color-light-point-10)',
    point20: 'var(--krds-color-light-point-20)',
    point30: 'var(--krds-color-light-point-30)',
    point40: 'var(--krds-color-light-point-40)',
    point50: 'var(--krds-color-light-point-50)',
    point60: 'var(--krds-color-light-point-60)',
    point70: 'var(--krds-color-light-point-70)',
    point80: 'var(--krds-color-light-point-80)',
    point90: 'var(--krds-color-light-point-90)',
    point95: 'var(--krds-color-light-point-95)',

    graphic10: 'var(--krds-color-light-graphic-10)',
    graphic30: 'var(--krds-color-light-graphic-30)',
    graphic50: 'var(--krds-color-light-graphic-50)',
    graphic70: 'var(--krds-color-light-graphic-70)',
    graphic90: 'var(--krds-color-light-graphic-90)',

    surface: {
      graySubtler: 'var(--krds-color-light-surface-gray-subtler)',
      graySubtle: 'var(--krds-color-light-surface-gray-subtle)',
      disabled: 'var(--krds-color-light-surface-disabled)',
      primarySubtler: 'var(--krds-color-light-surface-primary-subtler)',
      secondarySubtler: 'var(--krds-color-light-surface-secondary-subtler)',
      dangerSubtler: 'var(--krds-color-light-surface-danger-subtler)',
      warningSubtler: 'var(--krds-color-light-surface-warning-subtler)',
      successSubtler: 'var(--krds-color-light-surface-success-subtler)',
      informationSubtler: 'var(--krds-color-light-surface-information-subtler)',
      pointSubtler: 'var(--krds-color-light-surface-point-subtler)',
      white: 'var(--krds-color-light-surface-white)',
      inverse: 'var(--krds-color-light-surface-inverse)',
      whiteStatic: 'var(--krds-color-light-surface-white-static)',
      inverseStatic: 'var(--krds-color-light-surface-inverse-static)',
      whiteSubtle: 'var(--krds-color-light-surface-white-subtle)',
      whiteSubtler: 'var(--krds-color-light-surface-white-subtler)',
    },
    border: {
      grayLight: 'var(--krds-color-light-border-gray-light)',
      gray: 'var(--krds-color-light-border-gray)',
      secondaryLight: 'var(--krds-color-light-border-secondary-light)',
      dangerLight: 'var(--krds-color-light-border-danger-light)',
      danger: 'var(--krds-color-light-border-danger)',
      warningLight: 'var(--krds-color-light-border-warning-light)',
      warning: 'var(--krds-color-light-border-warning)',
      successLight: 'var(--krds-color-light-border-success-light)',
      success: 'var(--krds-color-light-border-success)',
      informationLight: 'var(--krds-color-light-border-information-light)',
      information: 'var(--krds-color-light-border-information)',
      grayDark: 'var(--krds-color-light-border-gray-dark)',
      primary: 'var(--krds-color-light-border-primary)',
      disabled: 'var(--krds-color-light-border-disabled)',
      grayDarker: 'var(--krds-color-light-border-gray-darker)',
      secondary: 'var(--krds-color-light-border-secondary)',
      inverse: 'var(--krds-color-light-border-inverse)',
      transparency: 'var(--krds-color-light-border-transparency)',
      primaryLight: 'var(--krds-color-light-border-primary-light)',
      point: 'var(--krds-color-light-border-point)',
      pointLight: 'var(--krds-color-light-border-point-light)',
    },
    divider: {
      grayLight: 'var(--krds-color-light-divider-gray-light)',
      gray: 'var(--krds-color-light-divider-gray)',
      grayDark: 'var(--krds-color-light-divider-gray-dark)',
      primary: 'var(--krds-color-light-divider-primary)',
      secondaryLight: 'var(--krds-color-light-divider-secondary-light)',
      secondary: 'var(--krds-color-light-divider-secondary)',
      error: 'var(--krds-color-light-divider-error)',
      primaryLight: 'var(--krds-color-light-divider-primary-light)',
      inverse: 'var(--krds-color-light-divider-inverse)',
      grayDarker: 'var(--krds-color-light-divider-gray-darker)',
      point: 'var(--krds-color-light-divider-point)',
    },
    text: {
      bolder: 'var(--krds-color-light-text-bolder)',
      subtle: 'var(--krds-color-light-text-subtle)',
      disabled: 'var(--krds-color-light-text-disabled)',
      disabledOn: 'var(--krds-color-light-text-disabled-on)',
      primary: 'var(--krds-color-light-text-primary)',
      secondary: 'var(--krds-color-light-text-secondary)',
      danger: 'var(--krds-color-light-text-danger)',
      warning: 'var(--krds-color-light-text-warning)',
      success: 'var(--krds-color-light-text-success)',
      information: 'var(--krds-color-light-text-information)',
      basic: 'var(--krds-color-light-text-basic)',
      point: 'var(--krds-color-light-text-point)',
      bolderInverse: 'var(--krds-color-light-text-bolder-inverse)',
      basicInverse: 'var(--krds-color-light-text-basic-inverse)',
      subtleInverse: 'var(--krds-color-light-text-subtle-inverse)',
      inverseStatic: 'var(--krds-color-light-text-inverse-static)',
      static: 'var(--krds-color-light-text-static)',
    },
    icon: {
      grayFill: 'var(--krds-color-light-icon-gray-fill)',
      inverse: 'var(--krds-color-light-icon-inverse)',
      primary: 'var(--krds-color-light-icon-primary)',
      secondary: 'var(--krds-color-light-icon-secondary)',
      point: 'var(--krds-color-light-icon-point)',
      danger: 'var(--krds-color-light-icon-danger)',
      warning: 'var(--krds-color-light-icon-warning)',
      success: 'var(--krds-color-light-icon-success)',
      information: 'var(--krds-color-light-icon-information)',
      grayLight: 'var(--krds-color-light-icon-gray-light)',
      disabled: 'var(--krds-color-light-icon-disabled)',
      disabledOn: 'var(--krds-color-light-icon-disabled-on)',
      inverseStatic: 'var(--krds-color-light-icon-inverse-static)',
      primaryStatic: 'var(--krds-color-light-icon-primary-static)',
      secondaryStatic: 'var(--krds-color-light-icon-secondary-static)',
      pointStatic: 'var(--krds-color-light-icon-point-static)',
      dangerStatic: 'var(--krds-color-light-icon-danger-static)',
      warningStatic: 'var(--krds-color-light-icon-warning-static)',
      successStatic: 'var(--krds-color-light-icon-success-static)',
      informationStatic: 'var(--krds-color-light-icon-information-static)',
      grayStatic: 'var(--krds-color-light-icon-gray-static)',
    },
    link: {
      default: 'var(--krds-color-light-link-default)',
      hover: 'var(--krds-color-light-link-hover)',
      pressed: 'var(--krds-color-light-link-pressed)',
      visited: 'var(--krds-color-light-link-visited)',
    },
    button: {
      primaryFill: 'var(--krds-color-light-button-primary-fill)',
      primaryFillHover: 'var(--krds-color-light-button-primary-fill-hover)',
      primaryFillPressed: 'var(--krds-color-light-button-primary-fill-pressed)',
      secondaryFill: 'var(--krds-color-light-button-secondary-fill)',
      secondaryFillHover: 'var(--krds-color-light-button-secondary-fill-hover)',
      secondaryFillPressed: 'var(--krds-color-light-button-secondary-fill-pressed)',
      secondaryBorder: 'var(--krds-color-light-button-secondary-border)',
      tertiaryFill: 'var(--krds-color-light-button-tertiary-fill)',
      tertiaryFillHover: 'var(--krds-color-light-button-tertiary-fill-hover)',
      tertiaryFillPressed: 'var(--krds-color-light-button-tertiary-fill-pressed)',
      disabledFill: 'var(--krds-color-light-button-disabled-fill)',
      disabledBorder: 'var(--krds-color-light-button-disabled-border)',
      textFillHover: 'var(--krds-color-light-button-text-fill-hover)',
      textFillPressed: 'var(--krds-color-light-button-text-fill-pressed)',
      textFill: 'var(--krds-color-light-button-text-fill)',
      textBorder: 'var(--krds-color-light-button-text-border)',
    },
    background: {
      white: 'var(--krds-color-light-background-white)',
      inverse: 'var(--krds-color-light-background-inverse)',
      graySubtler: 'var(--krds-color-light-background-gray-subtler)',
      graySubtle: 'var(--krds-color-light-background-gray-subtle)',
      dim: 'var(--krds-color-light-background-dim)',
    },
    element: {
      grayLighter: 'var(--krds-color-light-element-gray-lighter)',
      grayLight: 'var(--krds-color-light-element-gray-light)',
      gray: 'var(--krds-color-light-element-gray)',
      primaryLighter: 'var(--krds-color-light-element-primary-lighter)',
      primaryLight: 'var(--krds-color-light-element-primary-light)',
      primary: 'var(--krds-color-light-element-primary)',
      secondaryLighter: 'var(--krds-color-light-element-secondary-lighter)',
      secondaryLight: 'var(--krds-color-light-element-secondary-light)',
      secondary: 'var(--krds-color-light-element-secondary)',
      pointLighter: 'var(--krds-color-light-element-point-lighter)',
      pointLight: 'var(--krds-color-light-element-point-light)',
      point: 'var(--krds-color-light-element-point)',
      dangerLighter: 'var(--krds-color-light-element-danger-lighter)',
      danger: 'var(--krds-color-light-element-danger)',
      warningLighter: 'var(--krds-color-light-element-warning-lighter)',
      warning: 'var(--krds-color-light-element-warning)',
      successLighter: 'var(--krds-color-light-element-success-lighter)',
      success: 'var(--krds-color-light-element-success)',
      informationLighter: 'var(--krds-color-light-element-information-lighter)',
      information: 'var(--krds-color-light-element-information)',
      inverse: 'var(--krds-color-light-element-inverse)',
      grayDark: 'var(--krds-color-light-element-gray-dark)',
      inverseStatic: 'var(--krds-color-light-element-inverse-static)',
    },
    action: {
      white: 'var(--krds-color-light-action-white)',
      primary: 'var(--krds-color-light-action-primary)',
      primaryHover: 'var(--krds-color-light-action-primary-hover)',
      primaryPressed: 'var(--krds-color-light-action-primary-pressed)',
      secondary: 'var(--krds-color-light-action-secondary)',
      secondaryHover: 'var(--krds-color-light-action-secondary-hover)',
      secondaryPressed: 'var(--krds-color-light-action-secondary-pressed)',
      secondarySelected: 'var(--krds-color-light-action-secondary-selected)',
      secondaryOn: 'var(--krds-color-light-action-secondary-on)',
      secondaryOnHover: 'var(--krds-color-light-action-secondary-on-hover)',
      secondaryOnPressed: 'var(--krds-color-light-action-secondary-on-pressed)',
      secondaryOnSelected: 'var(--krds-color-light-action-secondary-on-selected)',
      secondaryActive: 'var(--krds-color-light-action-secondary-active)',
      primaryActive: 'var(--krds-color-light-action-primary-active)',
      disabled: 'var(--krds-color-light-action-disabled)',
      primarySelected: 'var(--krds-color-light-action-primary-selected)',
    },
    input: {
      border: 'var(--krds-color-light-input-border)',
      borderDisabled: 'var(--krds-color-light-input-border-disabled)',
      borderActive: 'var(--krds-color-light-input-border-active)',
      borderError: 'var(--krds-color-light-input-border-error)',
      surface: 'var(--krds-color-light-input-surface)',
      surfaceDisabled: 'var(--krds-color-light-input-surface-disabled)',
    },
    graphic: {
      blueSubtler: 'var(--krds-color-light-graphic-blue-subtler)',
      blueSubtle: 'var(--krds-color-light-graphic-blue-subtle)',
      blue: 'var(--krds-color-light-graphic-blue)',
      blueDark: 'var(--krds-color-light-graphic-blue-dark)',
      blueDarker: 'var(--krds-color-light-graphic-blue-darker)',
      redSubtler: 'var(--krds-color-light-graphic-red-subtler)',
      redSubtle: 'var(--krds-color-light-graphic-red-subtle)',
      red: 'var(--krds-color-light-graphic-red)',
      redDark: 'var(--krds-color-light-graphic-red-dark)',
      redDarker: 'var(--krds-color-light-graphic-red-darker)',
      brand: 'var(--krds-color-light-graphic-brand)',
    },
    alpha: {
      base100: 'var(--krds-color-light-alpha-white100)',
      base75: 'var(--krds-color-light-alpha-white75)',
      base50: 'var(--krds-color-light-alpha-white50)',
      base25: 'var(--krds-color-high-contrast-alpha-white25)',
      base10: 'var(--krds-color-high-contrast-alpha-white10)',
      base0: 'var(--krds-color-light-alpha-white0)',
      inverse100: 'var(--krds-color-light-alpha-black100)',
      inverse75: 'var(--krds-color-light-alpha-black75)',
      inverse50: 'var(--krds-color-light-alpha-black50)',
      inverse25: 'var(--krds-color-light-alpha-black25)',
      inverse10: 'var(--krds-color-light-alpha-black10)',
      inverse0: 'var(--krds-color-light-alpha-black0)',
      shadow1: '#0000000d',
      shadow2: '#00000014',
      shadow3: '#0000001f',
    },
  },
  borderWidths: {
    variableRegular: 'var(--krds-light-border-width-variable-regular)',
    variableMedium: 'var(--krds-light-border-width-variable-medium)',
    staticRegular: 'var(--krds-light-border-width-static-regular)',
    staticMedium: 'var(--krds-light-border-width-static-medium)',
  },
} as const;

const highContrastTheme = {
  ...commonTheme,
  colors: {
    primary5: 'var(--krds-color-high-contrast-primary-5)',
    primary10: 'var(--krds-color-high-contrast-primary-10)',
    primary20: 'var(--krds-color-high-contrast-primary-20)',
    primary30: 'var(--krds-color-high-contrast-primary-30)',
    primary40: 'var(--krds-color-high-contrast-primary-40)',
    primary50: 'var(--krds-color-high-contrast-primary-50)',
    primary60: 'var(--krds-color-high-contrast-primary-60)',
    primary70: 'var(--krds-color-high-contrast-primary-70)',
    primary80: 'var(--krds-color-high-contrast-primary-80)',
    primary90: 'var(--krds-color-high-contrast-primary-90)',
    primary95: 'var(--krds-color-high-contrast-primary-95)',

    secondary5: 'var(--krds-color-high-contrast-secondary-5)',
    secondary10: 'var(--krds-color-high-contrast-secondary-10)',
    secondary20: 'var(--krds-color-high-contrast-secondary-20)',
    secondary30: 'var(--krds-color-high-contrast-secondary-30)',
    secondary40: 'var(--krds-color-high-contrast-secondary-40)',
    secondary50: 'var(--krds-color-high-contrast-secondary-50)',
    secondary60: 'var(--krds-color-high-contrast-secondary-60)',
    secondary70: 'var(--krds-color-high-contrast-secondary-70)',
    secondary80: 'var(--krds-color-high-contrast-secondary-80)',
    secondary90: 'var(--krds-color-high-contrast-secondary-90)',
    secondary95: 'var(--krds-color-high-contrast-secondary-95)',

    gray0: 'var(--krds-color-high-contrast-gray-0)',
    gray5: 'var(--krds-color-high-contrast-gray-5)',
    gray10: 'var(--krds-color-high-contrast-gray-10)',
    gray20: 'var(--krds-color-high-contrast-gray-20)',
    gray30: 'var(--krds-color-high-contrast-gray-30)',
    gray40: 'var(--krds-color-high-contrast-gray-40)',
    gray50: 'var(--krds-color-high-contrast-gray-50)',
    gray60: 'var(--krds-color-high-contrast-gray-60)',
    gray70: 'var(--krds-color-high-contrast-gray-70)',
    gray80: 'var(--krds-color-high-contrast-gray-80)',
    gray90: 'var(--krds-color-high-contrast-gray-90)',
    gray95: 'var(--krds-color-high-contrast-gray-95)',
    gray100: 'var(--krds-color-high-contrast-gray-100)',

    alphaBlack100: 'var(--krds-color-high-contrast-alpha-black100)',
    alphaBlack75: 'var(--krds-color-high-contrast-alpha-black75)',
    alphaBlack50: 'var(--krds-color-high-contrast-alpha-black50)',
    alphaBlack25: 'var(--krds-color-high-contrast-alpha-black25)',
    alphaBlack10: 'var(--krds-color-high-contrast-alpha-black10)',
    alphaBlack0: 'var(--krds-color-high-contrast-alpha-black0)',

    alphaWhite100: 'var(--krds-color-high-contrast-alpha-white100)',
    alphaWhite75: 'var(--krds-color-high-contrast-alpha-white75)',
    alphaWhite50: 'var(--krds-color-high-contrast-alpha-white50)',
    alphaWhite25: 'var(--krds-color-high-contrast-alpha-white25)',
    alphaWhite10: 'var(--krds-color-high-contrast-alpha-white10)',
    alphaWhite0: 'var(--krds-color-high-contrast-alpha-white0)',

    danger5: 'var(--krds-color-high-contrast-danger-5)',
    danger10: 'var(--krds-color-high-contrast-danger-10)',
    danger20: 'var(--krds-color-high-contrast-danger-20)',
    danger30: 'var(--krds-color-high-contrast-danger-30)',
    danger40: 'var(--krds-color-high-contrast-danger-40)',
    danger50: 'var(--krds-color-high-contrast-danger-50)',
    danger60: 'var(--krds-color-high-contrast-danger-60)',
    danger70: 'var(--krds-color-high-contrast-danger-70)',
    danger80: 'var(--krds-color-high-contrast-danger-80)',
    danger90: 'var(--krds-color-high-contrast-danger-90)',
    danger95: 'var(--krds-color-high-contrast-danger-95)',

    information5: 'var(--krds-color-high-contrast-information-5)',
    information10: 'var(--krds-color-high-contrast-information-10)',
    information20: 'var(--krds-color-high-contrast-information-20)',
    information30: 'var(--krds-color-high-contrast-information-30)',
    information40: 'var(--krds-color-high-contrast-information-40)',
    information50: 'var(--krds-color-high-contrast-information-50)',
    information60: 'var(--krds-color-high-contrast-information-60)',
    information70: 'var(--krds-color-high-contrast-information-70)',
    information80: 'var(--krds-color-high-contrast-information-80)',
    information90: 'var(--krds-color-high-contrast-information-90)',
    information95: 'var(--krds-color-high-contrast-information-95)',

    warning5: 'var(--krds-color-high-contrast-warning-5)',
    warning10: 'var(--krds-color-high-contrast-warning-10)',
    warning20: 'var(--krds-color-high-contrast-warning-20)',
    warning30: 'var(--krds-color-high-contrast-warning-30)',
    warning40: 'var(--krds-color-high-contrast-warning-40)',
    warning50: 'var(--krds-color-high-contrast-warning-50)',
    warning60: 'var(--krds-color-high-contrast-warning-60)',
    warning70: 'var(--krds-color-high-contrast-warning-70)',
    warning80: 'var(--krds-color-high-contrast-warning-80)',
    warning90: 'var(--krds-color-high-contrast-warning-90)',
    warning95: 'var(--krds-color-high-contrast-warning-95)',

    success5: 'var(--krds-color-high-contrast-success-5)',
    success10: 'var(--krds-color-high-contrast-success-10)',
    success20: 'var(--krds-color-high-contrast-success-20)',
    success30: 'var(--krds-color-high-contrast-success-30)',
    success40: 'var(--krds-color-high-contrast-success-40)',
    success50: 'var(--krds-color-high-contrast-success-50)',
    success60: 'var(--krds-color-high-contrast-success-60)',
    success70: 'var(--krds-color-high-contrast-success-70)',
    success80: 'var(--krds-color-high-contrast-success-80)',
    success90: 'var(--krds-color-high-contrast-success-90)',
    success95: 'var(--krds-color-high-contrast-success-95)',

    point5: 'var(--krds-color-high-contrast-point-5)',
    point10: 'var(--krds-color-high-contrast-point-10)',
    point20: 'var(--krds-color-high-contrast-point-20)',
    point30: 'var(--krds-color-high-contrast-point-30)',
    point40: 'var(--krds-color-high-contrast-point-40)',
    point50: 'var(--krds-color-high-contrast-point-50)',
    point60: 'var(--krds-color-high-contrast-point-60)',
    point70: 'var(--krds-color-high-contrast-point-70)',
    point80: 'var(--krds-color-high-contrast-point-80)',
    point90: 'var(--krds-color-high-contrast-point-90)',
    point95: 'var(--krds-color-high-contrast-point-95)',

    graphic10: 'var(--krds-color-high-contrast-graphic-10)',
    graphic30: 'var(--krds-color-high-contrast-graphic-30)',
    graphic50: 'var(--krds-color-high-contrast-graphic-50)',
    graphic70: 'var(--krds-color-high-contrast-graphic-70)',
    graphic90: 'var(--krds-color-high-contrast-graphic-90)',

    surface: {
      graySubtler: 'var(--krds-high-contrast-color-surface-gray-subtler)',
      graySubtle: 'var(--krds-high-contrast-color-surface-gray-subtle)',
      disabled: 'var(--krds-high-contrast-color-surface-disabled)',
      primarySubtler: 'var(--krds-high-contrast-color-surface-primary-subtler)',
      secondarySubtler: 'var(--krds-high-contrast-color-surface-secondary-subtler)',
      dangerSubtler: 'var(--krds-high-contrast-color-surface-danger-subtler)',
      warningSubtler: 'var(--krds-high-contrast-color-surface-warning-subtler)',
      successSubtler: 'var(--krds-high-contrast-color-surface-success-subtler)',
      informationSubtler: 'var(--krds-high-contrast-color-surface-information-subtler)',
      pointSubtler: 'var(--krds-high-contrast-color-surface-point-subtler)',
      white: 'var(--krds-high-contrast-color-surface-white)',
      inverse: 'var(--krds-high-contrast-color-surface-inverse)',
      whiteStatic: 'var(--krds-high-contrast-color-surface-white-static)',
      inverseStatic: 'var(--krds-high-contrast-color-surface-inverse-static)',
      whiteSubtle: 'var(--krds-high-contrast-color-surface-white-subtle)',
      whiteSubtler: 'var(--krds-high-contrast-color-surface-white-subtler)',
    },

    border: {
      grayLight: 'var(--krds-high-contrast-color-border-gray-light)',
      gray: 'var(--krds-high-contrast-color-border-gray)',
      secondaryLight: 'var(--krds-high-contrast-color-border-secondary-light)',
      dangerLight: 'var(--krds-high-contrast-color-border-danger-light)',
      danger: 'var(--krds-high-contrast-color-border-danger)',
      warningLight: 'var(--krds-high-contrast-color-border-warning-light)',
      warning: 'var(--krds-high-contrast-color-border-warning)',
      successLight: 'var(--krds-high-contrast-color-border-success-light)',
      success: 'var(--krds-high-contrast-color-border-success)',
      informationLight: 'var(--krds-high-contrast-color-border-information-light)',
      information: 'var(--krds-high-contrast-color-border-information)',
      grayDark: 'var(--krds-high-contrast-color-border-gray-dark)',
      primary: 'var(--krds-high-contrast-color-border-primary)',
      disabled: 'var(--krds-high-contrast-color-border-disabled)',
      grayDarker: 'var(--krds-high-contrast-color-border-gray-darker)',
      secondary: 'var(--krds-high-contrast-color-border-secondary)',
      inverse: 'var(--krds-high-contrast-color-border-inverse)',
      transparency: 'var(--krds-high-contrast-color-border-transparency)',
      primaryLight: 'var(--krds-high-contrast-color-border-primary-light)',
      point: 'var(--krds-high-contrast-color-border-point)',
      pointLight: 'var(--krds-high-contrast-color-border-point-light)',
    },

    divider: {
      grayLight: 'var(--krds-high-contrast-color-divider-gray-light)',
      gray: 'var(--krds-high-contrast-color-divider-gray)',
      grayDark: 'var(--krds-high-contrast-color-divider-gray-dark)',
      primary: 'var(--krds-high-contrast-color-divider-primary)',
      secondaryLight: 'var(--krds-high-contrast-color-divider-secondary-light)',
      secondary: 'var(--krds-high-contrast-color-divider-secondary)',
      error: 'var(--krds-high-contrast-color-divider-error)',
      primaryLight: 'var(--krds-high-contrast-color-divider-primary-light)',
      inverse: 'var(--krds-high-contrast-color-divider-inverse)',
      grayDarker: 'var(--krds-high-contrast-color-divider-gray-darker)',
      point: 'var(--krds-high-contrast-color-divider-point)',
    },

    text: {
      bolder: 'var(--krds-high-contrast-color-text-bolder)',
      subtle: 'var(--krds-high-contrast-color-text-subtle)',
      disabled: 'var(--krds-high-contrast-color-text-disabled)',
      disabledOn: 'var(--krds-high-contrast-color-text-disabled-on)',
      primary: 'var(--krds-high-contrast-color-text-primary)',
      secondary: 'var(--krds-high-contrast-color-text-secondary)',
      danger: 'var(--krds-high-contrast-color-text-danger)',
      warning: 'var(--krds-high-contrast-color-text-warning)',
      success: 'var(--krds-high-contrast-color-text-success)',
      information: 'var(--krds-high-contrast-color-text-information)',
      basic: 'var(--krds-high-contrast-color-text-basic)',
      point: 'var(--krds-high-contrast-color-text-point)',
      bolderInverse: 'var(--krds-high-contrast-color-text-bolder-inverse)',
      basicInverse: 'var(--krds-high-contrast-color-text-basic-inverse)',
      subtleInverse: 'var(--krds-high-contrast-color-text-subtle-inverse)',
      inverseStatic: 'var(--krds-high-contrast-color-text-inverse-static)',
      static: 'var(--krds-high-contrast-color-text-static)',
    },

    icon: {
      grayFill: 'var(--krds-high-contrast-color-icon-gray-fill)',
      inverse: 'var(--krds-high-contrast-color-icon-inverse)',
      primary: 'var(--krds-high-contrast-color-icon-primary)',
      secondary: 'var(--krds-high-contrast-color-icon-secondary)',
      point: 'var(--krds-high-contrast-color-icon-point)',
      danger: 'var(--krds-high-contrast-color-icon-danger)',
      warning: 'var(--krds-high-contrast-color-icon-warning)',
      success: 'var(--krds-high-contrast-color-icon-success)',
      information: 'var(--krds-high-contrast-color-icon-information)',
      grayLight: 'var(--krds-high-contrast-color-icon-gray-light)',
      disabled: 'var(--krds-high-contrast-color-icon-disabled)',
      disabledOn: 'var(--krds-high-contrast-color-icon-disabled-on)',
      inverseStatic: 'var(--krds-high-contrast-color-icon-inverse-static)',
      primaryStatic: 'var(--krds-high-contrast-color-icon-primary-static)',
      secondaryStatic: 'var(--krds-high-contrast-color-icon-secondary-static)',
      pointStatic: 'var(--krds-high-contrast-color-icon-point-static)',
      dangerStatic: 'var(--krds-high-contrast-color-icon-danger-static)',
      warningStatic: 'var(--krds-high-contrast-color-icon-warning-static)',
      successStatic: 'var(--krds-high-contrast-color-icon-success-static)',
      informationStatic: 'var(--krds-high-contrast-color-icon-information-static)',
      grayStatic: 'var(--krds-high-contrast-color-icon-gray-static)',
    },

    link: {
      default: 'var(--krds-high-contrast-color-link-default)',
      hover: 'var(--krds-high-contrast-color-link-hover)',
      pressed: 'var(--krds-high-contrast-color-link-pressed)',
      visited: 'var(--krds-high-contrast-color-link-visited)',
    },

    button: {
      primaryFill: 'var(--krds-high-contrast-color-button-primary-fill)',
      primaryFillHover: 'var(--krds-high-contrast-color-button-primary-fill-hover)',
      primaryFillPressed: 'var(--krds-high-contrast-color-button-primary-fill-pressed)',
      secondaryFill: 'var(--krds-high-contrast-color-button-secondary-fill)',
      secondaryFillHover: 'var(--krds-high-contrast-color-button-secondary-fill-hover)',
      secondaryFillPressed: 'var(--krds-high-contrast-color-button-secondary-fill-pressed)',
      secondaryBorder: 'var(--krds-high-contrast-color-button-secondary-border)',
      tertiaryFill: 'var(--krds-high-contrast-color-button-tertiary-fill)',
      tertiaryFillHover: 'var(--krds-high-contrast-color-button-tertiary-fill-hover)',
      tertiaryFillPressed: 'var(--krds-high-contrast-color-button-tertiary-fill-pressed)',
      disabledFill: 'var(--krds-high-contrast-color-button-disabled-fill)',
      disabledBorder: 'var(--krds-high-contrast-color-button-disabled-border)',
      textFillHover: 'var(--krds-high-contrast-color-button-text-fill-hover)',
      textFillPressed: 'var(--krds-high-contrast-color-button-text-fill-pressed)',
      textFill: 'var(--krds-high-contrast-color-button-text-fill)',
      textBorder: 'var(--krds-high-contrast-color-button-text-border)',
    },

    background: {
      white: 'var(--krds-high-contrast-color-background-white)',
      inverse: 'var(--krds-high-contrast-color-background-inverse)',
      graySubtler: 'var(--krds-high-contrast-color-background-gray-subtler)',
      graySubtle: 'var(--krds-high-contrast-color-background-gray-subtle)',
      dim: 'var(--krds-high-contrast-color-background-dim)',
    },

    element: {
      grayLighter: 'var(--krds-high-contrast-color-element-gray-lighter)',
      grayLight: 'var(--krds-high-contrast-color-element-gray-light)',
      gray: 'var(--krds-high-contrast-color-element-gray)',
      primaryLighter: 'var(--krds-high-contrast-color-element-primary-lighter)',
      primaryLight: 'var(--krds-high-contrast-color-element-primary-light)',
      primary: 'var(--krds-high-contrast-color-element-primary)',
      secondaryLighter: 'var(--krds-high-contrast-color-element-secondary-lighter)',
      secondaryLight: 'var(--krds-high-contrast-color-element-secondary-light)',
      secondary: 'var(--krds-high-contrast-color-element-secondary)',
      pointLighter: 'var(--krds-high-contrast-color-element-point-lighter)',
      pointLight: 'var(--krds-high-contrast-color-element-point-light)',
      point: 'var(--krds-high-contrast-color-element-point)',
      dangerLighter: 'var(--krds-high-contrast-color-element-danger-lighter)',
      danger: 'var(--krds-high-contrast-color-element-danger)',
      warningLighter: 'var(--krds-high-contrast-color-element-warning-lighter)',
      warning: 'var(--krds-high-contrast-color-element-warning)',
      successLighter: 'var(--krds-high-contrast-color-element-success-lighter)',
      success: 'var(--krds-high-contrast-color-element-success)',
      informationLighter: 'var(--krds-high-contrast-color-element-information-lighter)',
      information: 'var(--krds-high-contrast-color-element-information)',
      inverse: 'var(--krds-high-contrast-color-element-inverse)',
      grayDark: 'var(--krds-high-contrast-color-element-gray-dark)',
      inverseStatic: 'var(--krds-high-contrast-color-element-inverse-static)',
    },

    action: {
      white: 'var(--krds-high-contrast-color-action-white)',
      primary: 'var(--krds-high-contrast-color-action-primary)',
      primaryHover: 'var(--krds-high-contrast-color-action-primary-hover)',
      primaryPressed: 'var(--krds-high-contrast-color-action-primary-pressed)',
      secondary: 'var(--krds-high-contrast-color-action-secondary)',
      secondaryHover: 'var(--krds-high-contrast-color-action-secondary-hover)',
      secondaryPressed: 'var(--krds-high-contrast-color-action-secondary-pressed)',
      secondarySelected: 'var(--krds-high-contrast-color-action-secondary-selected)',
      secondaryOn: 'var(--krds-high-contrast-color-action-secondary-on)',
      secondaryOnHover: 'var(--krds-high-contrast-color-action-secondary-on-hover)',
      secondaryOnPressed: 'var(--krds-high-contrast-color-action-secondary-on-pressed)',
      secondaryOnSelected: 'var(--krds-high-contrast-color-action-secondary-on-selected)',
      secondaryActive: 'var(--krds-high-contrast-color-action-secondary-active)',
      primaryActive: 'var(--krds-high-contrast-color-action-primary-active)',
      disabled: 'var(--krds-high-contrast-color-action-disabled)',
      primarySelected: 'var(--krds-high-contrast-color-action-primary-selected)',
    },

    input: {
      border: 'var(--krds-high-contrast-color-input-border)',
      borderDisabled: 'var(--krds-high-contrast-color-input-border-disabled)',
      borderActive: 'var(--krds-high-contrast-color-input-border-active)',
      borderError: 'var(--krds-high-contrast-color-input-border-error)',
      surface: 'var(--krds-high-contrast-color-input-surface)',
      surfaceDisabled: 'var(--krds-high-contrast-color-input-surface-disabled)',
    },

    graphic: {
      blueSubtler: 'var(--krds-high-contrast-color-graphic-blue-subtler)',
      blueSubtle: 'var(--krds-high-contrast-color-graphic-blue-subtle)',
      blue: 'var(--krds-high-contrast-color-graphic-blue)',
      blueDark: 'var(--krds-high-contrast-color-graphic-blue-dark)',
      blueDarker: 'var(--krds-high-contrast-color-graphic-blue-darker)',
      redSubtler: 'var(--krds-high-contrast-color-graphic-red-subtler)',
      redSubtle: 'var(--krds-high-contrast-color-graphic-red-subtle)',
      red: 'var(--krds-high-contrast-color-graphic-red)',
      redDark: 'var(--krds-high-contrast-color-graphic-red-dark)',
      redDarker: 'var(--krds-high-contrast-color-graphic-red-darker)',
      brand: 'var(--krds-high-contrast-color-graphic-brand)',
    },

    alpha: {
      base100: 'var(--krds-high-contrast-color-alpha-base100)',
      base75: 'var(--krds-high-contrast-color-alpha-base75)',
      base50: 'var(--krds-high-contrast-color-alpha-base50)',
      base25: 'var(--krds-high-contrast-color-alpha-base25)',
      base10: 'var(--krds-high-contrast-color-alpha-base10)',
      base0: 'var(--krds-high-contrast-color-alpha-base0)',
      inverse100: 'var(--krds-high-contrast-color-alpha-inverse100)',
      inverse75: 'var(--krds-high-contrast-color-alpha-inverse75)',
      inverse50: 'var(--krds-high-contrast-color-alpha-inverse50)',
      inverse25: 'var(--krds-high-contrast-color-alpha-inverse25)',
      inverse10: 'var(--krds-high-contrast-color-alpha-inverse10)',
      inverse0: 'var(--krds-high-contrast-color-alpha-inverse0)',
      shadow1: 'var(--krds-high-contrast-color-alpha-shadow1)',
      shadow2: 'var(--krds-high-contrast-color-alpha-shadow2)',
      shadow3: 'var(--krds-high-contrast-color-alpha-shadow3)',
    },
  },
  borderWidths: {
    variableRegular: 'var(--krds-high-contrast-border-width-variable-regular)',
    variableMedium: 'var(--krds-high-contrast-border-width-variable-medium)',
    staticRegular: 'var(--krds-high-contrast-border-width-static-regular)',
    staticMedium: 'var(--krds-high-contrast-border-width-static-medium)',
  },
} as const;

export { lightTheme, highContrastTheme };
